<?php

namespace EJP\AcademixBundle\Repository;

/**
 * DisponibiliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibiliteRepository extends \Doctrine\ORM\EntityRepository
{
}
