<?php

namespace EJP\AcademixBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends EntityRepository
{
    public function findCurrentEtude()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM EJPAcademixBundle:Etude e WHERE e.anneeScolaire = (SELECT max(et.anneeScolaire) FROM EJPAcademixBundle:Etude et)'
            )
            ->getResult();
    }

}
