<?php

namespace EJP\AcademixBundle\Repository;

/**
 * EtudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudeRepository extends \Doctrine\ORM\EntityRepository
{
}
