<?php

namespace EJP\AcademixBundle\Repository;

/**
 * HoraireRDVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoraireRDVRepository extends \Doctrine\ORM\EntityRepository
{
}
