<?php

namespace EJP\AcademixBundle\Repository;

/**
 * LastConRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LastConRepository extends \Doctrine\ORM\EntityRepository
{
}
