<?php

namespace EJP\AcademixBundle\Repository;

/**
 * SaddemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaddemRepository extends \Doctrine\ORM\EntityRepository
{
}
