<?php

namespace EJP\AcademixBundle\Repository;

/**
 * TestyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestyRepository extends \Doctrine\ORM\EntityRepository
{
}
