<?php

namespace EJP\AcademixBundle\Repository;

/**
 * TravailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravailRepository extends \Doctrine\ORM\EntityRepository
{
}
